---
services:
  redis:
    image: redis:7-alpine
    init: true

  devcontainer:
    image: jarppe/clj-devcontainer:latest
    restart: always
    volumes:
      - .:/home/${USER}/workspace
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    command: "sleep infinity"
